// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Alert struct {
	ID               string           `json:"id"`
	Type             string           `json:"type"`
	Severity         string           `json:"severity"`
	Title            string           `json:"title"`
	Message          string           `json:"message"`
	Metadata         []byte           `json:"metadata"`
	IsActive         bool             `json:"is_active"`
	AssignedToUserID *string          `json:"assigned_to_user_id"`
	ResolvedAt       pgtype.Timestamp `json:"resolved_at"`
	ResolvedByUserID *string          `json:"resolved_by_user_id"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
}

type AlertAction struct {
	ID               string           `json:"id"`
	Name             string           `json:"name"`
	DisplayName      string           `json:"display_name"`
	Description      *string          `json:"description"`
	IsStateAction    bool             `json:"is_state_action"`
	SeverityOverride *string          `json:"severity_override"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
}

type AlertConfig struct {
	ID                   string           `json:"id"`
	AlertType            string           `json:"alert_type"`
	IsEnabled            bool             `json:"is_enabled"`
	DefaultSeverity      string           `json:"default_severity"`
	AutoAssignEnabled    bool             `json:"auto_assign_enabled"`
	AutoAssignUserID     *string          `json:"auto_assign_user_id"`
	AutoAssignRule       *string          `json:"auto_assign_rule"`
	AutoAssignConditions []byte           `json:"auto_assign_conditions"`
	RetentionDays        *int32           `json:"retention_days"`
	AutoResolveAfterDays *int32           `json:"auto_resolve_after_days"`
	CleanupResolvedOnly  bool             `json:"cleanup_resolved_only"`
	NotificationEnabled  bool             `json:"notification_enabled"`
	EscalationEnabled    bool             `json:"escalation_enabled"`
	EscalationAfterHours *int32           `json:"escalation_after_hours"`
	AlertDelaySeconds    *int32           `json:"alert_delay_seconds"`
	Metadata             []byte           `json:"metadata"`
	Category             string           `json:"category"`
	CheckIntervalMinutes *int32           `json:"check_interval_minutes"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
	UpdatedAt            pgtype.Timestamp `json:"updated_at"`
}

type AlertHistory struct {
	ID        string           `json:"id"`
	AlertID   string           `json:"alert_id"`
	UserID    *string          `json:"user_id"`
	Action    string           `json:"action"`
	Metadata  []byte           `json:"metadata"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type AuditLog struct {
	ID           string           `json:"id"`
	Event        string           `json:"event"`
	UserID       *string          `json:"user_id"`
	TargetUserID *string          `json:"target_user_id"`
	IpAddress    *string          `json:"ip_address"`
	UserAgent    *string          `json:"user_agent"`
	RequestID    *string          `json:"request_id"`
	Details      *string          `json:"details"`
	Success      bool             `json:"success"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

type AutoEnrollmentToken struct {
	ID                 string           `json:"id"`
	TokenName          string           `json:"token_name"`
	TokenKey           string           `json:"token_key"`
	TokenSecret        string           `json:"token_secret"`
	CreatedByUserID    *string          `json:"created_by_user_id"`
	IsActive           bool             `json:"is_active"`
	AllowedIpRanges    []string         `json:"allowed_ip_ranges"`
	MaxHostsPerDay     int32            `json:"max_hosts_per_day"`
	HostsCreatedToday  int32            `json:"hosts_created_today"`
	LastResetDate      pgtype.Date      `json:"last_reset_date"`
	DefaultHostGroupID *string          `json:"default_host_group_id"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	LastUsedAt         pgtype.Timestamp `json:"last_used_at"`
	ExpiresAt          pgtype.Timestamp `json:"expires_at"`
	Metadata           []byte           `json:"metadata"`
	Scopes             []byte           `json:"scopes"`
}

type ComplianceProfile struct {
	ID          string           `json:"id"`
	Name        string           `json:"name"`
	Type        string           `json:"type"`
	OsFamily    *string          `json:"os_family"`
	Version     *string          `json:"version"`
	Description *string          `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type ComplianceResult struct {
	ID          string           `json:"id"`
	ScanID      string           `json:"scan_id"`
	RuleID      string           `json:"rule_id"`
	Status      string           `json:"status"`
	Finding     *string          `json:"finding"`
	Actual      *string          `json:"actual"`
	Expected    *string          `json:"expected"`
	Remediation *string          `json:"remediation"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type ComplianceRule struct {
	ID          string  `json:"id"`
	ProfileID   string  `json:"profile_id"`
	RuleRef     string  `json:"rule_ref"`
	Title       string  `json:"title"`
	Description *string `json:"description"`
	Rationale   *string `json:"rationale"`
	Severity    *string `json:"severity"`
	Section     *string `json:"section"`
	Remediation *string `json:"remediation"`
}

type ComplianceScan struct {
	ID            string           `json:"id"`
	HostID        string           `json:"host_id"`
	ProfileID     string           `json:"profile_id"`
	StartedAt     pgtype.Timestamp `json:"started_at"`
	CompletedAt   pgtype.Timestamp `json:"completed_at"`
	Status        string           `json:"status"`
	TotalRules    int32            `json:"total_rules"`
	Passed        int32            `json:"passed"`
	Failed        int32            `json:"failed"`
	Warnings      int32            `json:"warnings"`
	Skipped       int32            `json:"skipped"`
	NotApplicable int32            `json:"not_applicable"`
	Score         *float64         `json:"score"`
	ErrorMessage  *string          `json:"error_message"`
	RawOutput     *string          `json:"raw_output"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type DashboardLayout struct {
	UserID        string           `json:"user_id"`
	StatsColumns  int32            `json:"stats_columns"`
	ChartsColumns int32            `json:"charts_columns"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type DashboardPreference struct {
	ID        string           `json:"id"`
	UserID    string           `json:"user_id"`
	CardID    string           `json:"card_id"`
	Enabled   bool             `json:"enabled"`
	Order     int32            `json:"order"`
	ColSpan   int32            `json:"col_span"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type DockerContainer struct {
	ID          string           `json:"id"`
	HostID      string           `json:"host_id"`
	ContainerID string           `json:"container_id"`
	Name        string           `json:"name"`
	ImageID     *string          `json:"image_id"`
	ImageName   string           `json:"image_name"`
	ImageTag    string           `json:"image_tag"`
	Status      string           `json:"status"`
	State       *string          `json:"state"`
	Ports       []byte           `json:"ports"`
	Labels      []byte           `json:"labels"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	StartedAt   pgtype.Timestamp `json:"started_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	LastChecked pgtype.Timestamp `json:"last_checked"`
}

type DockerImage struct {
	ID          string           `json:"id"`
	Repository  string           `json:"repository"`
	Tag         string           `json:"tag"`
	ImageID     string           `json:"image_id"`
	Digest      *string          `json:"digest"`
	SizeBytes   *int64           `json:"size_bytes"`
	Source      string           `json:"source"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	LastPulled  pgtype.Timestamp `json:"last_pulled"`
	LastChecked pgtype.Timestamp `json:"last_checked"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type DockerImageUpdate struct {
	ID               string           `json:"id"`
	ImageID          string           `json:"image_id"`
	CurrentTag       string           `json:"current_tag"`
	AvailableTag     string           `json:"available_tag"`
	IsSecurityUpdate bool             `json:"is_security_update"`
	Severity         *string          `json:"severity"`
	ChangelogUrl     *string          `json:"changelog_url"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
}

type DockerNetwork struct {
	ID             string           `json:"id"`
	HostID         string           `json:"host_id"`
	NetworkID      string           `json:"network_id"`
	Name           string           `json:"name"`
	Driver         string           `json:"driver"`
	Scope          string           `json:"scope"`
	Ipv6Enabled    bool             `json:"ipv6_enabled"`
	Internal       bool             `json:"internal"`
	Attachable     bool             `json:"attachable"`
	Ingress        bool             `json:"ingress"`
	ConfigOnly     bool             `json:"config_only"`
	Labels         []byte           `json:"labels"`
	Ipam           []byte           `json:"ipam"`
	ContainerCount int32            `json:"container_count"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	LastChecked    pgtype.Timestamp `json:"last_checked"`
}

type DockerVolume struct {
	ID          string           `json:"id"`
	HostID      string           `json:"host_id"`
	VolumeID    string           `json:"volume_id"`
	Name        string           `json:"name"`
	Driver      string           `json:"driver"`
	Mountpoint  *string          `json:"mountpoint"`
	Renderer    *string          `json:"renderer"`
	Scope       string           `json:"scope"`
	Labels      []byte           `json:"labels"`
	Options     []byte           `json:"options"`
	SizeBytes   *int64           `json:"size_bytes"`
	RefCount    int32            `json:"ref_count"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	LastChecked pgtype.Timestamp `json:"last_checked"`
}

type Host struct {
	ID                           string             `json:"id"`
	MachineID                    *string            `json:"machine_id"`
	FriendlyName                 string             `json:"friendly_name"`
	Ip                           *string            `json:"ip"`
	OsType                       string             `json:"os_type"`
	OsVersion                    string             `json:"os_version"`
	Architecture                 *string            `json:"architecture"`
	LastUpdate                   pgtype.Timestamp   `json:"last_update"`
	Status                       string             `json:"status"`
	CreatedAt                    pgtype.Timestamp   `json:"created_at"`
	UpdatedAt                    pgtype.Timestamp   `json:"updated_at"`
	ApiID                        string             `json:"api_id"`
	ApiKey                       string             `json:"api_key"`
	AgentVersion                 *string            `json:"agent_version"`
	AutoUpdate                   bool               `json:"auto_update"`
	CpuCores                     *int32             `json:"cpu_cores"`
	CpuModel                     *string            `json:"cpu_model"`
	DiskDetails                  []byte             `json:"disk_details"`
	DnsServers                   []byte             `json:"dns_servers"`
	GatewayIp                    *string            `json:"gateway_ip"`
	Hostname                     *string            `json:"hostname"`
	KernelVersion                *string            `json:"kernel_version"`
	InstalledKernelVersion       *string            `json:"installed_kernel_version"`
	LoadAverage                  []byte             `json:"load_average"`
	NetworkInterfaces            []byte             `json:"network_interfaces"`
	RamInstalled                 *float64           `json:"ram_installed"`
	SelinuxStatus                *string            `json:"selinux_status"`
	SwapSize                     *float64           `json:"swap_size"`
	SystemUptime                 *string            `json:"system_uptime"`
	BootTime                     pgtype.Timestamptz `json:"boot_time"`
	Notes                        *string            `json:"notes"`
	NeedsReboot                  *bool              `json:"needs_reboot"`
	RebootReason                 *string            `json:"reboot_reason"`
	DockerEnabled                bool               `json:"docker_enabled"`
	ComplianceEnabled            bool               `json:"compliance_enabled"`
	ComplianceOnDemandOnly       bool               `json:"compliance_on_demand_only"`
	ComplianceOpenscapEnabled    bool               `json:"compliance_openscap_enabled"`
	ComplianceDockerBenchEnabled bool               `json:"compliance_docker_bench_enabled"`
	ComplianceScannerStatus      []byte             `json:"compliance_scanner_status"`
	ComplianceScannerUpdatedAt   pgtype.Timestamp   `json:"compliance_scanner_updated_at"`
	ComplianceDefaultProfileID   *string            `json:"compliance_default_profile_id"`
	HostDownAlertsEnabled        *bool              `json:"host_down_alerts_enabled"`
	ExpectedPlatform             *string            `json:"expected_platform"`
	PackageManager               *string            `json:"package_manager"`
	PrimaryInterface             *string            `json:"primary_interface"`
	AwaitingPostPatchReportRunID *string            `json:"awaiting_post_patch_report_run_id"`
	PackagesHash                 *string            `json:"packages_hash"`
	ReposHash                    *string            `json:"repos_hash"`
	InterfacesHash               *string            `json:"interfaces_hash"`
	HostnameHash                 *string            `json:"hostname_hash"`
	DockerHash                   *string            `json:"docker_hash"`
	ComplianceHash               *string            `json:"compliance_hash"`
	LastFullReportAt             pgtype.Timestamp   `json:"last_full_report_at"`
}

type HostGroup struct {
	ID          string           `json:"id"`
	Name        string           `json:"name"`
	Description *string          `json:"description"`
	Color       *string          `json:"color"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type HostGroupMembership struct {
	ID          string           `json:"id"`
	HostID      string           `json:"host_id"`
	HostGroupID string           `json:"host_group_id"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type HostPackage struct {
	ID                 string           `json:"id"`
	HostID             string           `json:"host_id"`
	PackageID          string           `json:"package_id"`
	CurrentVersion     string           `json:"current_version"`
	AvailableVersion   *string          `json:"available_version"`
	NeedsUpdate        bool             `json:"needs_update"`
	IsSecurityUpdate   bool             `json:"is_security_update"`
	LastChecked        pgtype.Timestamp `json:"last_checked"`
	WuaGuid            *string          `json:"wua_guid"`
	WuaKb              *string          `json:"wua_kb"`
	WuaSeverity        *string          `json:"wua_severity"`
	WuaCategories      []byte           `json:"wua_categories"`
	WuaDescription     *string          `json:"wua_description"`
	WuaSupportUrl      *string          `json:"wua_support_url"`
	WuaRevisionNumber  *int32           `json:"wua_revision_number"`
	WuaDateInstalled   pgtype.Timestamp `json:"wua_date_installed"`
	WuaInstallResult   *string          `json:"wua_install_result"`
	SourceRepositoryID *string          `json:"source_repository_id"`
}

type HostPendingConfig struct {
	HostID                       string           `json:"host_id"`
	DockerEnabled                *bool            `json:"docker_enabled"`
	ComplianceEnabled            *bool            `json:"compliance_enabled"`
	ComplianceOnDemandOnly       *bool            `json:"compliance_on_demand_only"`
	ComplianceOpenscapEnabled    *bool            `json:"compliance_openscap_enabled"`
	ComplianceDockerBenchEnabled *bool            `json:"compliance_docker_bench_enabled"`
	CreatedAt                    pgtype.Timestamp `json:"created_at"`
	UpdatedAt                    pgtype.Timestamp `json:"updated_at"`
}

type HostRepository struct {
	ID           string           `json:"id"`
	HostID       string           `json:"host_id"`
	RepositoryID string           `json:"repository_id"`
	IsEnabled    bool             `json:"is_enabled"`
	LastChecked  pgtype.Timestamp `json:"last_checked"`
}

type JobHistory struct {
	ID            string           `json:"id"`
	JobID         string           `json:"job_id"`
	QueueName     string           `json:"queue_name"`
	JobName       string           `json:"job_name"`
	HostID        *string          `json:"host_id"`
	ApiID         *string          `json:"api_id"`
	Status        string           `json:"status"`
	AttemptNumber int32            `json:"attempt_number"`
	ErrorMessage  *string          `json:"error_message"`
	Output        []byte           `json:"output"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	CompletedAt   pgtype.Timestamp `json:"completed_at"`
}

type MvPackageStat struct {
	PackageID       string `json:"package_id"`
	TotalInstalls   int32  `json:"total_installs"`
	UpdatesNeeded   int32  `json:"updates_needed"`
	SecurityUpdates int32  `json:"security_updates"`
}

type NotificationDeliveryLog struct {
	ID                string           `json:"id"`
	EventFingerprint  string           `json:"event_fingerprint"`
	ReferenceType     string           `json:"reference_type"`
	ReferenceID       string           `json:"reference_id"`
	DestinationID     string           `json:"destination_id"`
	EventType         string           `json:"event_type"`
	Status            string           `json:"status"`
	ErrorMessage      *string          `json:"error_message"`
	AttemptCount      int32            `json:"attempt_count"`
	ProviderMessageID *string          `json:"provider_message_id"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
}

type NotificationDestination struct {
	ID              string           `json:"id"`
	ChannelType     string           `json:"channel_type"`
	DisplayName     string           `json:"display_name"`
	ConfigEncrypted string           `json:"config_encrypted"`
	Enabled         bool             `json:"enabled"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

type NotificationRoute struct {
	ID            string           `json:"id"`
	DestinationID string           `json:"destination_id"`
	EventTypes    []byte           `json:"event_types"`
	MinSeverity   string           `json:"min_severity"`
	HostGroupIds  []byte           `json:"host_group_ids"`
	HostIds       []byte           `json:"host_ids"`
	MatchRules    []byte           `json:"match_rules"`
	Enabled       bool             `json:"enabled"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type Package struct {
	ID            string           `json:"id"`
	Name          string           `json:"name"`
	Description   *string          `json:"description"`
	Category      *string          `json:"category"`
	LatestVersion *string          `json:"latest_version"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type PatchPolicy struct {
	ID             string           `json:"id"`
	Name           string           `json:"name"`
	Description    *string          `json:"description"`
	PatchDelayType string           `json:"patch_delay_type"`
	DelayMinutes   *int32           `json:"delay_minutes"`
	FixedTimeUtc   *string          `json:"fixed_time_utc"`
	Timezone       *string          `json:"timezone"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

type PatchPolicyAssignment struct {
	ID            string           `json:"id"`
	PatchPolicyID string           `json:"patch_policy_id"`
	TargetType    string           `json:"target_type"`
	TargetID      string           `json:"target_id"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type PatchPolicyExclusion struct {
	ID            string           `json:"id"`
	PatchPolicyID string           `json:"patch_policy_id"`
	HostID        string           `json:"host_id"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type PatchRun struct {
	ID                string           `json:"id"`
	HostID            string           `json:"host_id"`
	JobID             string           `json:"job_id"`
	PatchType         string           `json:"patch_type"`
	PackageName       *string          `json:"package_name"`
	PackageNames      []byte           `json:"package_names"`
	Status            string           `json:"status"`
	ShellOutput       string           `json:"shell_output"`
	ErrorMessage      *string          `json:"error_message"`
	StartedAt         pgtype.Timestamp `json:"started_at"`
	CompletedAt       pgtype.Timestamp `json:"completed_at"`
	ScheduledAt       pgtype.Timestamp `json:"scheduled_at"`
	TriggeredByUserID *string          `json:"triggered_by_user_id"`
	ApprovedByUserID  *string          `json:"approved_by_user_id"`
	DryRun            bool             `json:"dry_run"`
	PackagesAffected  []byte           `json:"packages_affected"`
	PolicyID          *string          `json:"policy_id"`
	PolicyName        *string          `json:"policy_name"`
	PolicySnapshot    []byte           `json:"policy_snapshot"`
	ValidationRunID   *string          `json:"validation_run_id"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
}

type ReleaseNotesAcceptance struct {
	ID         string           `json:"id"`
	UserID     string           `json:"user_id"`
	Version    string           `json:"version"`
	AcceptedAt pgtype.Timestamp `json:"accepted_at"`
}

type Repository struct {
	ID           string           `json:"id"`
	Name         string           `json:"name"`
	Url          string           `json:"url"`
	Distribution string           `json:"distribution"`
	Components   string           `json:"components"`
	RepoType     string           `json:"repo_type"`
	IsActive     bool             `json:"is_active"`
	IsSecure     bool             `json:"is_secure"`
	Priority     *int32           `json:"priority"`
	Description  *string          `json:"description"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type RolePermission struct {
	ID                      string           `json:"id"`
	Role                    string           `json:"role"`
	CanViewDashboard        bool             `json:"can_view_dashboard"`
	CanViewHosts            bool             `json:"can_view_hosts"`
	CanManageHosts          bool             `json:"can_manage_hosts"`
	CanViewPackages         bool             `json:"can_view_packages"`
	CanManagePackages       bool             `json:"can_manage_packages"`
	CanViewUsers            bool             `json:"can_view_users"`
	CanManageUsers          bool             `json:"can_manage_users"`
	CanManageSuperusers     bool             `json:"can_manage_superusers"`
	CanViewReports          bool             `json:"can_view_reports"`
	CanExportData           bool             `json:"can_export_data"`
	CanManageSettings       bool             `json:"can_manage_settings"`
	CanManageNotifications  bool             `json:"can_manage_notifications"`
	CanViewNotificationLogs bool             `json:"can_view_notification_logs"`
	CanManagePatching       bool             `json:"can_manage_patching"`
	CanManageCompliance     bool             `json:"can_manage_compliance"`
	CanManageDocker         bool             `json:"can_manage_docker"`
	CanManageAlerts         bool             `json:"can_manage_alerts"`
	CanManageAutomation     bool             `json:"can_manage_automation"`
	CanUseRemoteAccess      bool             `json:"can_use_remote_access"`
	CanManageBilling        bool             `json:"can_manage_billing"`
	CreatedAt               pgtype.Timestamp `json:"created_at"`
	UpdatedAt               pgtype.Timestamp `json:"updated_at"`
}

type ScheduledReport struct {
	ID             string           `json:"id"`
	Name           string           `json:"name"`
	CronExpr       string           `json:"cron_expr"`
	Enabled        bool             `json:"enabled"`
	Definition     []byte           `json:"definition"`
	DestinationIds []byte           `json:"destination_ids"`
	Timezone       string           `json:"timezone"`
	NextRunAt      pgtype.Timestamp `json:"next_run_at"`
	LastRunAt      pgtype.Timestamp `json:"last_run_at"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

type ScheduledReportRun struct {
	ID                string           `json:"id"`
	ScheduledReportID string           `json:"scheduled_report_id"`
	RunAt             pgtype.Timestamp `json:"run_at"`
	Status            string           `json:"status"`
	ErrorMessage      *string          `json:"error_message"`
	SummaryHash       *string          `json:"summary_hash"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
}

type Setting struct {
	ID                              string           `json:"id"`
	ServerUrl                       string           `json:"server_url"`
	ServerProtocol                  string           `json:"server_protocol"`
	ServerHost                      string           `json:"server_host"`
	ServerPort                      int32            `json:"server_port"`
	CreatedAt                       pgtype.Timestamp `json:"created_at"`
	UpdatedAt                       pgtype.Timestamp `json:"updated_at"`
	UpdateInterval                  int32            `json:"update_interval"`
	AutoUpdate                      bool             `json:"auto_update"`
	DefaultComplianceMode           string           `json:"default_compliance_mode"`
	ComplianceScanInterval          int32            `json:"compliance_scan_interval"`
	PackageCacheRefreshMode         string           `json:"package_cache_refresh_mode"`
	PackageCacheRefreshMaxAge       int32            `json:"package_cache_refresh_max_age"`
	GithubRepoUrl                   string           `json:"github_repo_url"`
	SshKeyPath                      *string          `json:"ssh_key_path"`
	RepositoryType                  string           `json:"repository_type"`
	LastUpdateCheck                 pgtype.Timestamp `json:"last_update_check"`
	LatestVersion                   *string          `json:"latest_version"`
	UpdateAvailable                 bool             `json:"update_available"`
	SignupEnabled                   bool             `json:"signup_enabled"`
	DefaultUserRole                 string           `json:"default_user_role"`
	IgnoreSslSelfSigned             bool             `json:"ignore_ssl_self_signed"`
	LogoDark                        *string          `json:"logo_dark"`
	LogoLight                       *string          `json:"logo_light"`
	Favicon                         *string          `json:"favicon"`
	LogoDarkData                    []byte           `json:"logo_dark_data"`
	LogoLightData                   []byte           `json:"logo_light_data"`
	FaviconData                     []byte           `json:"favicon_data"`
	LogoDarkContentType             *string          `json:"logo_dark_content_type"`
	LogoLightContentType            *string          `json:"logo_light_content_type"`
	FaviconContentType              *string          `json:"favicon_content_type"`
	MetricsEnabled                  bool             `json:"metrics_enabled"`
	MetricsAnonymousID              *string          `json:"metrics_anonymous_id"`
	MetricsLastSent                 pgtype.Timestamp `json:"metrics_last_sent"`
	ShowGithubVersionOnLogin        bool             `json:"show_github_version_on_login"`
	AiEnabled                       bool             `json:"ai_enabled"`
	AiProvider                      string           `json:"ai_provider"`
	AiModel                         *string          `json:"ai_model"`
	AiApiKey                        *string          `json:"ai_api_key"`
	AlertsEnabled                   bool             `json:"alerts_enabled"`
	DiscordOauthEnabled             bool             `json:"discord_oauth_enabled"`
	DiscordClientID                 *string          `json:"discord_client_id"`
	DiscordClientSecret             *string          `json:"discord_client_secret"`
	DiscordRedirectUri              *string          `json:"discord_redirect_uri"`
	DiscordButtonText               *string          `json:"discord_button_text"`
	OidcEnabled                     bool             `json:"oidc_enabled"`
	OidcIssuerUrl                   *string          `json:"oidc_issuer_url"`
	OidcClientID                    *string          `json:"oidc_client_id"`
	OidcClientSecret                *string          `json:"oidc_client_secret"`
	OidcRedirectUri                 *string          `json:"oidc_redirect_uri"`
	OidcScopes                      *string          `json:"oidc_scopes"`
	OidcAutoCreateUsers             bool             `json:"oidc_auto_create_users"`
	OidcDefaultRole                 *string          `json:"oidc_default_role"`
	OidcDisableLocalAuth            bool             `json:"oidc_disable_local_auth"`
	OidcButtonText                  *string          `json:"oidc_button_text"`
	OidcSyncRoles                   bool             `json:"oidc_sync_roles"`
	OidcAdminGroup                  *string          `json:"oidc_admin_group"`
	OidcSuperadminGroup             *string          `json:"oidc_superadmin_group"`
	OidcHostManagerGroup            *string          `json:"oidc_host_manager_group"`
	OidcReadonlyGroup               *string          `json:"oidc_readonly_group"`
	OidcUserGroup                   *string          `json:"oidc_user_group"`
	OidcEnforceHttps                bool             `json:"oidc_enforce_https"`
	OidcTrustUnverifiedEmail        bool             `json:"oidc_trust_unverified_email"`
	MaxLoginAttempts                *int32           `json:"max_login_attempts"`
	LockoutDurationMinutes          *int32           `json:"lockout_duration_minutes"`
	SessionInactivityTimeoutMinutes *int32           `json:"session_inactivity_timeout_minutes"`
	PatchRunStallTimeoutMinutes     *int32           `json:"patch_run_stall_timeout_minutes"`
	AgentReportsRetentionDays       *int32           `json:"agent_reports_retention_days"`
	TfaMaxRememberSessions          *int32           `json:"tfa_max_remember_sessions"`
	PasswordMinLength               *int32           `json:"password_min_length"`
	PasswordRequireUppercase        *bool            `json:"password_require_uppercase"`
	PasswordRequireLowercase        *bool            `json:"password_require_lowercase"`
	PasswordRequireNumber           *bool            `json:"password_require_number"`
	PasswordRequireSpecial          *bool            `json:"password_require_special"`
	EnableHsts                      *bool            `json:"enable_hsts"`
	JsonBodyLimit                   *string          `json:"json_body_limit"`
	AgentUpdateBodyLimit            *string          `json:"agent_update_body_limit"`
	ComplianceBodyLimit             *string          `json:"compliance_body_limit"`
	AgentPingBodyLimit              *string          `json:"agent_ping_body_limit"`
	DbTransactionLongTimeout        *int32           `json:"db_transaction_long_timeout"`
	CorsOrigin                      *string          `json:"cors_origin"`
	EnableLogging                   *bool            `json:"enable_logging"`
	LogLevel                        *string          `json:"log_level"`
	Timezone                        *string          `json:"timezone"`
	JwtExpiresIn                    *string          `json:"jwt_expires_in"`
	MaxTfaAttempts                  *int32           `json:"max_tfa_attempts"`
	TfaLockoutDurationMinutes       *int32           `json:"tfa_lockout_duration_minutes"`
	TfaRememberMeExpiresIn          *string          `json:"tfa_remember_me_expires_in"`
	TrustProxy                      *bool            `json:"trust_proxy"`
	RateLimitWindowMs               *int32           `json:"rate_limit_window_ms"`
	RateLimitMax                    *int32           `json:"rate_limit_max"`
	AuthRateLimitWindowMs           *int32           `json:"auth_rate_limit_window_ms"`
	AuthRateLimitMax                *int32           `json:"auth_rate_limit_max"`
	AgentRateLimitWindowMs          *int32           `json:"agent_rate_limit_window_ms"`
	AgentRateLimitMax               *int32           `json:"agent_rate_limit_max"`
	PasswordRateLimitWindowMs       *int32           `json:"password_rate_limit_window_ms"`
	PasswordRateLimitMax            *int32           `json:"password_rate_limit_max"`
	AuthBrowserSessionCookies       *bool            `json:"auth_browser_session_cookies"`
}

type SystemStatistic struct {
	ID                  string           `json:"id"`
	UniquePackagesCount int32            `json:"unique_packages_count"`
	UniqueSecurityCount int32            `json:"unique_security_count"`
	TotalPackages       int32            `json:"total_packages"`
	TotalHosts          int32            `json:"total_hosts"`
	HostsNeedingUpdates int32            `json:"hosts_needing_updates"`
	Timestamp           pgtype.Timestamp `json:"timestamp"`
}

type UpdateHistory struct {
	ID                string           `json:"id"`
	HostID            string           `json:"host_id"`
	PackagesCount     int32            `json:"packages_count"`
	SecurityCount     int32            `json:"security_count"`
	TotalPackages     *int32           `json:"total_packages"`
	PayloadSizeKb     *float64         `json:"payload_size_kb"`
	ExecutionTime     *float64         `json:"execution_time"`
	Timestamp         pgtype.Timestamp `json:"timestamp"`
	Status            string           `json:"status"`
	ErrorMessage      *string          `json:"error_message"`
	ReportType        string           `json:"report_type"`
	SectionsSent      []string         `json:"sections_sent"`
	SectionsUnchanged []string         `json:"sections_unchanged"`
	AgentExecutionMs  *int32           `json:"agent_execution_ms"`
}

type User struct {
	ID                     string           `json:"id"`
	Username               string           `json:"username"`
	Email                  string           `json:"email"`
	PasswordHash           *string          `json:"password_hash"`
	Role                   string           `json:"role"`
	IsActive               bool             `json:"is_active"`
	LastLogin              pgtype.Timestamp `json:"last_login"`
	CreatedAt              pgtype.Timestamp `json:"created_at"`
	UpdatedAt              pgtype.Timestamp `json:"updated_at"`
	TfaBackupCodes         *string          `json:"tfa_backup_codes"`
	TfaEnabled             bool             `json:"tfa_enabled"`
	TfaSecret              *string          `json:"tfa_secret"`
	FirstName              *string          `json:"first_name"`
	LastName               *string          `json:"last_name"`
	ThemePreference        *string          `json:"theme_preference"`
	ColorTheme             *string          `json:"color_theme"`
	Locale                 *string          `json:"locale"`
	UiPreferences          []byte           `json:"ui_preferences"`
	OidcSub                *string          `json:"oidc_sub"`
	OidcProvider           *string          `json:"oidc_provider"`
	AvatarUrl              *string          `json:"avatar_url"`
	DiscordID              *string          `json:"discord_id"`
	DiscordUsername        *string          `json:"discord_username"`
	DiscordAvatar          *string          `json:"discord_avatar"`
	DiscordLinkedAt        pgtype.Timestamp `json:"discord_linked_at"`
	NewsletterSubscribed   bool             `json:"newsletter_subscribed"`
	NewsletterSubscribedAt pgtype.Timestamp `json:"newsletter_subscribed_at"`
}

type UserSession struct {
	ID                string           `json:"id"`
	UserID            string           `json:"user_id"`
	RefreshToken      string           `json:"refresh_token"`
	AccessTokenHash   *string          `json:"access_token_hash"`
	IpAddress         *string          `json:"ip_address"`
	UserAgent         *string          `json:"user_agent"`
	DeviceFingerprint *string          `json:"device_fingerprint"`
	DeviceID          *string          `json:"device_id"`
	LastActivity      pgtype.Timestamp `json:"last_activity"`
	ExpiresAt         pgtype.Timestamp `json:"expires_at"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	IsRevoked         bool             `json:"is_revoked"`
	TfaRememberMe     bool             `json:"tfa_remember_me"`
	TfaBypassUntil    pgtype.Timestamp `json:"tfa_bypass_until"`
	LoginCount        int32            `json:"login_count"`
	LastLoginIp       *string          `json:"last_login_ip"`
}

type UserTrustedDevice struct {
	ID         string           `json:"id"`
	UserID     string           `json:"user_id"`
	TokenHash  string           `json:"token_hash"`
	DeviceID   *string          `json:"device_id"`
	UserAgent  *string          `json:"user_agent"`
	IpAddress  *string          `json:"ip_address"`
	Label      *string          `json:"label"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	LastUsedAt pgtype.Timestamp `json:"last_used_at"`
	ExpiresAt  pgtype.Timestamp `json:"expires_at"`
	IsRevoked  bool             `json:"is_revoked"`
}
