// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveAdmins = `-- name: CountActiveAdmins :one
SELECT COUNT(*) FROM users WHERE role = 'admin' AND is_active = true
`

func (q *Queries) CountActiveAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAdmins = `-- name: CountAdmins :one
SELECT COUNT(*) FROM users WHERE role IN ('admin', 'superadmin') AND is_active = true
`

func (q *Queries) CountAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSuperadmins = `-- name: CountSuperadmins :one
SELECT COUNT(*) FROM users WHERE role = 'superadmin' AND is_active = true
`

func (q *Queries) CountSuperadmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSuperadmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDiscordUser = `-- name: CreateDiscordUser :exec
INSERT INTO users (
    id, username, email, password_hash, role, is_active, created_at, updated_at,
    tfa_enabled, first_name, last_name, theme_preference, color_theme,
    discord_id, discord_username, discord_avatar, discord_linked_at
) VALUES (
    $1, $2, $3, NULL, $4, true, $5, $6,
    false, $7, $8, 'dark', 'cyber_blue',
    $9, $10, $11, $12
)
`

type CreateDiscordUserParams struct {
	ID              string           `json:"id"`
	Username        string           `json:"username"`
	Email           string           `json:"email"`
	Role            string           `json:"role"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	FirstName       *string          `json:"first_name"`
	LastName        *string          `json:"last_name"`
	DiscordID       *string          `json:"discord_id"`
	DiscordUsername *string          `json:"discord_username"`
	DiscordAvatar   *string          `json:"discord_avatar"`
	DiscordLinkedAt pgtype.Timestamp `json:"discord_linked_at"`
}

func (q *Queries) CreateDiscordUser(ctx context.Context, arg CreateDiscordUserParams) error {
	_, err := q.db.Exec(ctx, createDiscordUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.Role,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.FirstName,
		arg.LastName,
		arg.DiscordID,
		arg.DiscordUsername,
		arg.DiscordAvatar,
		arg.DiscordLinkedAt,
	)
	return err
}

const createOidcUser = `-- name: CreateOidcUser :exec
INSERT INTO users (
    id, username, email, password_hash, role, is_active, created_at, updated_at,
    tfa_enabled, first_name, last_name, theme_preference, color_theme,
    oidc_sub, oidc_provider, avatar_url
) VALUES (
    $1, $2, $3, NULL, $4, true, $5, $6,
    false, $7, $8, 'dark', 'cyber_blue',
    $9, $10, $11
)
`

type CreateOidcUserParams struct {
	ID           string           `json:"id"`
	Username     string           `json:"username"`
	Email        string           `json:"email"`
	Role         string           `json:"role"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	FirstName    *string          `json:"first_name"`
	LastName     *string          `json:"last_name"`
	OidcSub      *string          `json:"oidc_sub"`
	OidcProvider *string          `json:"oidc_provider"`
	AvatarUrl    *string          `json:"avatar_url"`
}

func (q *Queries) CreateOidcUser(ctx context.Context, arg CreateOidcUserParams) error {
	_, err := q.db.Exec(ctx, createOidcUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.Role,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.FirstName,
		arg.LastName,
		arg.OidcSub,
		arg.OidcProvider,
		arg.AvatarUrl,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
    id, username, email, password_hash, role, is_active, created_at, updated_at,
    tfa_enabled, first_name, last_name, theme_preference, color_theme
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $12, $13
)
`

type CreateUserParams struct {
	ID              string           `json:"id"`
	Username        string           `json:"username"`
	Email           string           `json:"email"`
	PasswordHash    *string          `json:"password_hash"`
	Role            string           `json:"role"`
	IsActive        bool             `json:"is_active"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	TfaEnabled      bool             `json:"tfa_enabled"`
	FirstName       *string          `json:"first_name"`
	LastName        *string          `json:"last_name"`
	ThemePreference *string          `json:"theme_preference"`
	ColorTheme      *string          `json:"color_theme"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.TfaEnabled,
		arg.FirstName,
		arg.LastName,
		arg.ThemePreference,
		arg.ColorTheme,
	)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const disableTfa = `-- name: DisableTfa :exec
UPDATE users SET tfa_enabled = false, tfa_secret = NULL, tfa_backup_codes = NULL, updated_at = NOW() WHERE id = $1
`

func (q *Queries) DisableTfa(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, disableTfa, id)
	return err
}

const existsByUsernameOrEmail = `-- name: ExistsByUsernameOrEmail :one
SELECT COUNT(*) > 0 FROM users
WHERE (LOWER(username) = LOWER($1) OR LOWER(email) = LOWER($2))
AND ($3::text IS NULL OR id != $3)
`

type ExistsByUsernameOrEmailParams struct {
	Username      string  `json:"username"`
	Email         string  `json:"email"`
	ExcludeUserID *string `json:"exclude_user_id"`
}

func (q *Queries) ExistsByUsernameOrEmail(ctx context.Context, arg ExistsByUsernameOrEmailParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsByUsernameOrEmail, arg.Username, arg.Email, arg.ExcludeUserID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const getUserByDiscordID = `-- name: GetUserByDiscordID :one
SELECT id, username, email, password_hash, role, is_active, last_login, created_at, updated_at, tfa_backup_codes, tfa_enabled, tfa_secret, first_name, last_name, theme_preference, color_theme, locale, ui_preferences, oidc_sub, oidc_provider, avatar_url, discord_id, discord_username, discord_avatar, discord_linked_at, newsletter_subscribed, newsletter_subscribed_at FROM users WHERE discord_id = $1
`

func (q *Queries) GetUserByDiscordID(ctx context.Context, discordID *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByDiscordID, discordID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TfaBackupCodes,
		&i.TfaEnabled,
		&i.TfaSecret,
		&i.FirstName,
		&i.LastName,
		&i.ThemePreference,
		&i.ColorTheme,
		&i.Locale,
		&i.UiPreferences,
		&i.OidcSub,
		&i.OidcProvider,
		&i.AvatarUrl,
		&i.DiscordID,
		&i.DiscordUsername,
		&i.DiscordAvatar,
		&i.DiscordLinkedAt,
		&i.NewsletterSubscribed,
		&i.NewsletterSubscribedAt,
	)
	return i, err
}

const getUserByDiscordIDOrEmail = `-- name: GetUserByDiscordIDOrEmail :one
SELECT id, username, email, password_hash, role, is_active, last_login, created_at, updated_at, tfa_backup_codes, tfa_enabled, tfa_secret, first_name, last_name, theme_preference, color_theme, locale, ui_preferences, oidc_sub, oidc_provider, avatar_url, discord_id, discord_username, discord_avatar, discord_linked_at, newsletter_subscribed, newsletter_subscribed_at FROM users
WHERE discord_id = $1 OR (LOWER(email) = LOWER($2) AND $2 != '')
ORDER BY CASE WHEN discord_id = $1 THEN 0 ELSE 1 END
LIMIT 1
`

type GetUserByDiscordIDOrEmailParams struct {
	DiscordID *string `json:"discord_id"`
	Lower     string  `json:"lower"`
}

func (q *Queries) GetUserByDiscordIDOrEmail(ctx context.Context, arg GetUserByDiscordIDOrEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByDiscordIDOrEmail, arg.DiscordID, arg.Lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TfaBackupCodes,
		&i.TfaEnabled,
		&i.TfaSecret,
		&i.FirstName,
		&i.LastName,
		&i.ThemePreference,
		&i.ColorTheme,
		&i.Locale,
		&i.UiPreferences,
		&i.OidcSub,
		&i.OidcProvider,
		&i.AvatarUrl,
		&i.DiscordID,
		&i.DiscordUsername,
		&i.DiscordAvatar,
		&i.DiscordLinkedAt,
		&i.NewsletterSubscribed,
		&i.NewsletterSubscribedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, role, is_active, last_login, created_at, updated_at, tfa_backup_codes, tfa_enabled, tfa_secret, first_name, last_name, theme_preference, color_theme, locale, ui_preferences, oidc_sub, oidc_provider, avatar_url, discord_id, discord_username, discord_avatar, discord_linked_at, newsletter_subscribed, newsletter_subscribed_at FROM users WHERE LOWER(email) = LOWER($1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TfaBackupCodes,
		&i.TfaEnabled,
		&i.TfaSecret,
		&i.FirstName,
		&i.LastName,
		&i.ThemePreference,
		&i.ColorTheme,
		&i.Locale,
		&i.UiPreferences,
		&i.OidcSub,
		&i.OidcProvider,
		&i.AvatarUrl,
		&i.DiscordID,
		&i.DiscordUsername,
		&i.DiscordAvatar,
		&i.DiscordLinkedAt,
		&i.NewsletterSubscribed,
		&i.NewsletterSubscribedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, role, is_active, last_login, created_at, updated_at, tfa_backup_codes, tfa_enabled, tfa_secret, first_name, last_name, theme_preference, color_theme, locale, ui_preferences, oidc_sub, oidc_provider, avatar_url, discord_id, discord_username, discord_avatar, discord_linked_at, newsletter_subscribed, newsletter_subscribed_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TfaBackupCodes,
		&i.TfaEnabled,
		&i.TfaSecret,
		&i.FirstName,
		&i.LastName,
		&i.ThemePreference,
		&i.ColorTheme,
		&i.Locale,
		&i.UiPreferences,
		&i.OidcSub,
		&i.OidcProvider,
		&i.AvatarUrl,
		&i.DiscordID,
		&i.DiscordUsername,
		&i.DiscordAvatar,
		&i.DiscordLinkedAt,
		&i.NewsletterSubscribed,
		&i.NewsletterSubscribedAt,
	)
	return i, err
}

const getUserByOidcSub = `-- name: GetUserByOidcSub :one
SELECT id, username, email, password_hash, role, is_active, last_login, created_at, updated_at, tfa_backup_codes, tfa_enabled, tfa_secret, first_name, last_name, theme_preference, color_theme, locale, ui_preferences, oidc_sub, oidc_provider, avatar_url, discord_id, discord_username, discord_avatar, discord_linked_at, newsletter_subscribed, newsletter_subscribed_at FROM users WHERE oidc_sub = $1
`

func (q *Queries) GetUserByOidcSub(ctx context.Context, oidcSub *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByOidcSub, oidcSub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TfaBackupCodes,
		&i.TfaEnabled,
		&i.TfaSecret,
		&i.FirstName,
		&i.LastName,
		&i.ThemePreference,
		&i.ColorTheme,
		&i.Locale,
		&i.UiPreferences,
		&i.OidcSub,
		&i.OidcProvider,
		&i.AvatarUrl,
		&i.DiscordID,
		&i.DiscordUsername,
		&i.DiscordAvatar,
		&i.DiscordLinkedAt,
		&i.NewsletterSubscribed,
		&i.NewsletterSubscribedAt,
	)
	return i, err
}

const getUserByOidcSubOrEmail = `-- name: GetUserByOidcSubOrEmail :one
SELECT id, username, email, password_hash, role, is_active, last_login, created_at, updated_at, tfa_backup_codes, tfa_enabled, tfa_secret, first_name, last_name, theme_preference, color_theme, locale, ui_preferences, oidc_sub, oidc_provider, avatar_url, discord_id, discord_username, discord_avatar, discord_linked_at, newsletter_subscribed, newsletter_subscribed_at FROM users
WHERE oidc_sub = $1 OR (LOWER(email) = LOWER($2) AND $2 != '')
ORDER BY CASE WHEN oidc_sub = $1 THEN 0 ELSE 1 END
LIMIT 1
`

type GetUserByOidcSubOrEmailParams struct {
	OidcSub *string `json:"oidc_sub"`
	Lower   string  `json:"lower"`
}

// The "$2 != ”" guard mirrors GetUserByDiscordIDOrEmail. Without it an IdP
// asserting an empty email participates in the email branch, which is junk
// input rather than a takeover (the oidc_sub cross-check blocks a second such
// login) but should not reach account matching at all.
func (q *Queries) GetUserByOidcSubOrEmail(ctx context.Context, arg GetUserByOidcSubOrEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByOidcSubOrEmail, arg.OidcSub, arg.Lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TfaBackupCodes,
		&i.TfaEnabled,
		&i.TfaSecret,
		&i.FirstName,
		&i.LastName,
		&i.ThemePreference,
		&i.ColorTheme,
		&i.Locale,
		&i.UiPreferences,
		&i.OidcSub,
		&i.OidcProvider,
		&i.AvatarUrl,
		&i.DiscordID,
		&i.DiscordUsername,
		&i.DiscordAvatar,
		&i.DiscordLinkedAt,
		&i.NewsletterSubscribed,
		&i.NewsletterSubscribedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password_hash, role, is_active, last_login, created_at, updated_at, tfa_backup_codes, tfa_enabled, tfa_secret, first_name, last_name, theme_preference, color_theme, locale, ui_preferences, oidc_sub, oidc_provider, avatar_url, discord_id, discord_username, discord_avatar, discord_linked_at, newsletter_subscribed, newsletter_subscribed_at FROM users WHERE LOWER(username) = LOWER($1)
`

func (q *Queries) GetUserByUsername(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TfaBackupCodes,
		&i.TfaEnabled,
		&i.TfaSecret,
		&i.FirstName,
		&i.LastName,
		&i.ThemePreference,
		&i.ColorTheme,
		&i.Locale,
		&i.UiPreferences,
		&i.OidcSub,
		&i.OidcProvider,
		&i.AvatarUrl,
		&i.DiscordID,
		&i.DiscordUsername,
		&i.DiscordAvatar,
		&i.DiscordLinkedAt,
		&i.NewsletterSubscribed,
		&i.NewsletterSubscribedAt,
	)
	return i, err
}

const getUserByUsernameOrEmail = `-- name: GetUserByUsernameOrEmail :one
SELECT id, username, email, password_hash, role, is_active, last_login, created_at, updated_at, tfa_backup_codes, tfa_enabled, tfa_secret, first_name, last_name, theme_preference, color_theme, locale, ui_preferences, oidc_sub, oidc_provider, avatar_url, discord_id, discord_username, discord_avatar, discord_linked_at, newsletter_subscribed, newsletter_subscribed_at FROM users
WHERE LOWER(username) = LOWER($1) OR LOWER(email) = LOWER($1)
ORDER BY CASE WHEN LOWER(username) = LOWER($1) THEN 0 ELSE 1 END
LIMIT 1
`

func (q *Queries) GetUserByUsernameOrEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsernameOrEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TfaBackupCodes,
		&i.TfaEnabled,
		&i.TfaSecret,
		&i.FirstName,
		&i.LastName,
		&i.ThemePreference,
		&i.ColorTheme,
		&i.Locale,
		&i.UiPreferences,
		&i.OidcSub,
		&i.OidcProvider,
		&i.AvatarUrl,
		&i.DiscordID,
		&i.DiscordUsername,
		&i.DiscordAvatar,
		&i.DiscordLinkedAt,
		&i.NewsletterSubscribed,
		&i.NewsletterSubscribedAt,
	)
	return i, err
}

const listActiveUsers = `-- name: ListActiveUsers :many
SELECT id, username, email, password_hash, role, is_active, last_login, created_at, updated_at, tfa_backup_codes, tfa_enabled, tfa_secret, first_name, last_name, theme_preference, color_theme, locale, ui_preferences, oidc_sub, oidc_provider, avatar_url, discord_id, discord_username, discord_avatar, discord_linked_at, newsletter_subscribed, newsletter_subscribed_at FROM users WHERE is_active = true ORDER BY username
`

func (q *Queries) ListActiveUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listActiveUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.IsActive,
			&i.LastLogin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TfaBackupCodes,
			&i.TfaEnabled,
			&i.TfaSecret,
			&i.FirstName,
			&i.LastName,
			&i.ThemePreference,
			&i.ColorTheme,
			&i.Locale,
			&i.UiPreferences,
			&i.OidcSub,
			&i.OidcProvider,
			&i.AvatarUrl,
			&i.DiscordID,
			&i.DiscordUsername,
			&i.DiscordAvatar,
			&i.DiscordLinkedAt,
			&i.NewsletterSubscribed,
			&i.NewsletterSubscribedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, password_hash, role, is_active, last_login, created_at, updated_at, tfa_backup_codes, tfa_enabled, tfa_secret, first_name, last_name, theme_preference, color_theme, locale, ui_preferences, oidc_sub, oidc_provider, avatar_url, discord_id, discord_username, discord_avatar, discord_linked_at, newsletter_subscribed, newsletter_subscribed_at FROM users ORDER BY username LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.IsActive,
			&i.LastLogin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TfaBackupCodes,
			&i.TfaEnabled,
			&i.TfaSecret,
			&i.FirstName,
			&i.LastName,
			&i.ThemePreference,
			&i.ColorTheme,
			&i.Locale,
			&i.UiPreferences,
			&i.OidcSub,
			&i.OidcProvider,
			&i.AvatarUrl,
			&i.DiscordID,
			&i.DiscordUsername,
			&i.DiscordAvatar,
			&i.DiscordLinkedAt,
			&i.NewsletterSubscribed,
			&i.NewsletterSubscribedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setNewsletterSubscribed = `-- name: SetNewsletterSubscribed :exec
UPDATE users SET newsletter_subscribed = true, newsletter_subscribed_at = NOW(), updated_at = NOW() WHERE id = $1
`

func (q *Queries) SetNewsletterSubscribed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, setNewsletterSubscribed, id)
	return err
}

const updateLastLogin = `-- name: UpdateLastLogin :exec
UPDATE users SET last_login = $1 WHERE id = $2
`

type UpdateLastLoginParams struct {
	LastLogin pgtype.Timestamp `json:"last_login"`
	ID        string           `json:"id"`
}

func (q *Queries) UpdateLastLogin(ctx context.Context, arg UpdateLastLoginParams) error {
	_, err := q.db.Exec(ctx, updateLastLogin, arg.LastLogin, arg.ID)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users SET password_hash = $1, updated_at = NOW() WHERE id = $2
`

type UpdatePasswordParams struct {
	PasswordHash *string `json:"password_hash"`
	ID           string  `json:"id"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.PasswordHash, arg.ID)
	return err
}

const updateTfaBackupCodes = `-- name: UpdateTfaBackupCodes :exec
UPDATE users SET tfa_backup_codes = $1, updated_at = NOW() WHERE id = $2
`

type UpdateTfaBackupCodesParams struct {
	TfaBackupCodes *string `json:"tfa_backup_codes"`
	ID             string  `json:"id"`
}

func (q *Queries) UpdateTfaBackupCodes(ctx context.Context, arg UpdateTfaBackupCodesParams) error {
	_, err := q.db.Exec(ctx, updateTfaBackupCodes, arg.TfaBackupCodes, arg.ID)
	return err
}

const updateTfaEnabled = `-- name: UpdateTfaEnabled :exec
UPDATE users SET tfa_enabled = $1, tfa_backup_codes = $2, updated_at = NOW() WHERE id = $3
`

type UpdateTfaEnabledParams struct {
	TfaEnabled     bool    `json:"tfa_enabled"`
	TfaBackupCodes *string `json:"tfa_backup_codes"`
	ID             string  `json:"id"`
}

func (q *Queries) UpdateTfaEnabled(ctx context.Context, arg UpdateTfaEnabledParams) error {
	_, err := q.db.Exec(ctx, updateTfaEnabled, arg.TfaEnabled, arg.TfaBackupCodes, arg.ID)
	return err
}

const updateTfaSecret = `-- name: UpdateTfaSecret :exec
UPDATE users SET tfa_secret = $1, updated_at = NOW() WHERE id = $2
`

type UpdateTfaSecretParams struct {
	TfaSecret *string `json:"tfa_secret"`
	ID        string  `json:"id"`
}

func (q *Queries) UpdateTfaSecret(ctx context.Context, arg UpdateTfaSecretParams) error {
	_, err := q.db.Exec(ctx, updateTfaSecret, arg.TfaSecret, arg.ID)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users SET
    username = $1, email = $2, role = $3, is_active = $4,
    updated_at = $5, first_name = $6, last_name = $7,
    theme_preference = $8, color_theme = $9
WHERE id = $10
`

type UpdateUserParams struct {
	Username        string           `json:"username"`
	Email           string           `json:"email"`
	Role            string           `json:"role"`
	IsActive        bool             `json:"is_active"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	FirstName       *string          `json:"first_name"`
	LastName        *string          `json:"last_name"`
	ThemePreference *string          `json:"theme_preference"`
	ColorTheme      *string          `json:"color_theme"`
	ID              string           `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.Username,
		arg.Email,
		arg.Role,
		arg.IsActive,
		arg.UpdatedAt,
		arg.FirstName,
		arg.LastName,
		arg.ThemePreference,
		arg.ColorTheme,
		arg.ID,
	)
	return err
}

const updateUserDiscordLink = `-- name: UpdateUserDiscordLink :exec
UPDATE users SET
    discord_id = $1, discord_username = $2, discord_avatar = $3,
    discord_linked_at = $4, updated_at = NOW()
WHERE id = $5
`

type UpdateUserDiscordLinkParams struct {
	DiscordID       *string          `json:"discord_id"`
	DiscordUsername *string          `json:"discord_username"`
	DiscordAvatar   *string          `json:"discord_avatar"`
	DiscordLinkedAt pgtype.Timestamp `json:"discord_linked_at"`
	ID              string           `json:"id"`
}

func (q *Queries) UpdateUserDiscordLink(ctx context.Context, arg UpdateUserDiscordLinkParams) error {
	_, err := q.db.Exec(ctx, updateUserDiscordLink,
		arg.DiscordID,
		arg.DiscordUsername,
		arg.DiscordAvatar,
		arg.DiscordLinkedAt,
		arg.ID,
	)
	return err
}

const updateUserDiscordProfile = `-- name: UpdateUserDiscordProfile :exec
UPDATE users SET
    last_login = $1, discord_username = $2, discord_avatar = $3, updated_at = NOW()
WHERE id = $4
`

type UpdateUserDiscordProfileParams struct {
	LastLogin       pgtype.Timestamp `json:"last_login"`
	DiscordUsername *string          `json:"discord_username"`
	DiscordAvatar   *string          `json:"discord_avatar"`
	ID              string           `json:"id"`
}

func (q *Queries) UpdateUserDiscordProfile(ctx context.Context, arg UpdateUserDiscordProfileParams) error {
	_, err := q.db.Exec(ctx, updateUserDiscordProfile,
		arg.LastLogin,
		arg.DiscordUsername,
		arg.DiscordAvatar,
		arg.ID,
	)
	return err
}

const updateUserDiscordUnlink = `-- name: UpdateUserDiscordUnlink :exec
UPDATE users SET
    discord_id = NULL, discord_username = NULL, discord_avatar = NULL,
    discord_linked_at = NULL, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateUserDiscordUnlink(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, updateUserDiscordUnlink, id)
	return err
}

const updateUserOidcLink = `-- name: UpdateUserOidcLink :exec
UPDATE users SET
    oidc_sub = $1, oidc_provider = $2, avatar_url = $3, updated_at = NOW()
WHERE id = $4
`

type UpdateUserOidcLinkParams struct {
	OidcSub      *string `json:"oidc_sub"`
	OidcProvider *string `json:"oidc_provider"`
	AvatarUrl    *string `json:"avatar_url"`
	ID           string  `json:"id"`
}

func (q *Queries) UpdateUserOidcLink(ctx context.Context, arg UpdateUserOidcLinkParams) error {
	_, err := q.db.Exec(ctx, updateUserOidcLink,
		arg.OidcSub,
		arg.OidcProvider,
		arg.AvatarUrl,
		arg.ID,
	)
	return err
}

const updateUserOidcProfile = `-- name: UpdateUserOidcProfile :exec
UPDATE users SET
    last_login = $1, avatar_url = COALESCE($2, avatar_url),
    first_name = COALESCE($3, first_name), last_name = COALESCE($4, last_name),
    role = $5, updated_at = NOW()
WHERE id = $6
`

type UpdateUserOidcProfileParams struct {
	LastLogin pgtype.Timestamp `json:"last_login"`
	AvatarUrl *string          `json:"avatar_url"`
	FirstName *string          `json:"first_name"`
	LastName  *string          `json:"last_name"`
	Role      string           `json:"role"`
	ID        string           `json:"id"`
}

func (q *Queries) UpdateUserOidcProfile(ctx context.Context, arg UpdateUserOidcProfileParams) error {
	_, err := q.db.Exec(ctx, updateUserOidcProfile,
		arg.LastLogin,
		arg.AvatarUrl,
		arg.FirstName,
		arg.LastName,
		arg.Role,
		arg.ID,
	)
	return err
}

const updateUserPreferences = `-- name: UpdateUserPreferences :exec
UPDATE users SET
    theme_preference = COALESCE($1::text, theme_preference),
    color_theme = COALESCE($2::text, color_theme),
    ui_preferences = COALESCE($3::jsonb, ui_preferences),
    updated_at = NOW()
WHERE id = $4
`

type UpdateUserPreferencesParams struct {
	ThemePreference *string `json:"theme_preference"`
	ColorTheme      *string `json:"color_theme"`
	UiPreferences   []byte  `json:"ui_preferences"`
	ID              string  `json:"id"`
}

func (q *Queries) UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) error {
	_, err := q.db.Exec(ctx, updateUserPreferences,
		arg.ThemePreference,
		arg.ColorTheme,
		arg.UiPreferences,
		arg.ID,
	)
	return err
}
